version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    command: npm start
  admin:
    build: ./admin
    ports:
      - "8080:80"
    depends_on:
      - backend
